name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version-file: ./wasm/go.mod
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Build
        run: |
          cd frontend
          npm install
          npm run build-wasm
          npm run fetch-wasm-exec
          npm run build
      - name: Publish
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: frontend/dist
          clean: true
          token: ${{ secrets.GITHUB_TOKEN }}
